### PR TITLE
update to fix Form Issue

### PR DESCRIPTION
**Pull request by SimonGreenhill**
This corrects the colspec for Form/Value.

I can't seem to get the glottolog version to show as v4.0? Could you please check this @xrotwang

### CODE REVIEW

**Review by LinguList — COMMENTED** [review]
@SimonGreenhill, as long as this is pending: can you add the line "-" -> "+" to your orthoprofile? This would make all elements acceptable (although there's still some work to do on that profile).

**Comment by chrzyki** [comment]
@SimonGreenhill what path do you have in (or the respective path for OSX)

```
$ cat ~/.config/pylexibank/config.ini
```

for Glottolog? What does `git describe` say when you run it in the path for Glottolog specified in `config.ini`?

**Comment by SimonGreenhill** [comment]
Ahh, thanks @chrzyki thats the problem. I've got that fixed now. @LinguList, fixed too, thanks :)

**Review by xrotwang — CHANGES_REQUESTED** [review]
There's still the `None` in the travis badge, which we'd need to track down.

**Comment by SimonGreenhill** [comment]
Was there a bug fix somewhere in a package I need to update?

**Comment by xrotwang** [comment]
hm. don't know. There's potentially an overly generic `except` in https://github.com/lexibank/pylexibank/blob/96502588cf0d2378fe9678ffa0b1ed22fe51387a/src/pylexibank/dataset.py#L241-L247

**Comment by SimonGreenhill** [comment]
ok, it's the regex that's failing:
self.git_repo.remotes.origin.url  =  "https://github.com/lexibank/birchallchapacuran"
... so no \.git^

**Comment by xrotwang** [comment]
oh. good catch!

**Comment by xrotwang** [comment]
Noted: https://github.com/lexibank/pylexibank/issues/102#issuecomment-510045311

**Comment by SimonGreenhill** [comment]
ok, i've fixed this manually for now.

**Pull request merged**
