### PR TITLE
fixing errors

### PR DESCRIPTION
**Pull request by LinguList**

### CODE REVIEW

**Comment by LinguList** [comment]
please see the simple statement that I used there, which fixes this issue, maybe we need a short update on the major functions, some kind of internal tutorial here?

**Comment by SimonGreenhill** [comment]
Awesome, looks good. Thanks @LinguList!

**Comment by xrotwang** [comment]
Refactoring pylexibank to make use of the core functionality in cldfbench could be done in two ways:
- Backwards compatible - will require a couple of "hacks", circumventing the "better" practices imposed by cldfbench or
- backwards incompatible.

I'd opt for the second solution, even if that means pylexibank 2.x. It seems we already aggregated quite a few changes in pylexibank where it's not entirely clear whether they are backwards compatible anyway. Keeping an eye on breaking changes will also become easier with core functionality factored out to a 100% tested cldfbench package.

**Comment by SimonGreenhill** [comment]
Yes, let's break things now.

**Comment by LinguList** [comment]
I agree with lexibank 2.0. I'd also like to bring in changes there, which are in `add_forms_from_value`, namely what I suggested: that one can define split_forms more explicitly on a per-dataset basis, to also make sure things are comparable. 

Question is only: do we need to change the datasets that we have now drastically then? If so, let's make a list of core datasets we want to work on now, to split work. I have already 26 in our CALC datasets, of which I already serve as some kind of a patron. For the others, we would need to make sure that patrons of a dataset commit to internal deadlines of updating the data, and that we have a way to communicate which things are still needed to be done. This is also pinging @tresoldi and @chrzyki as part of our core lexibank team.

**Comment by xrotwang** [comment]
@LinguList Depends on what you consider drastic. We certainly will have to "touch" all of them (since we wouldn't want to leave datasets left behind in `pylexibank<2` land, right?)
So I'd imagine small edits in
- `lexibank_*.py` and
- `setup.py`

and re-running `makecldf` to be the standard for most of the datasets.

**Comment by LinguList** [comment]
Okay, so I would then say: it is also time to make a priority list of datasets to be included here, and that we fix the patron question, i.e., that we also write the patron to the metadata.json here, that contributors are looked into, etc., etc.

My main point is: this is a good way to also make sure that our lexibank core team (the fantastic five) takes the chance to catch up in consistently cleaning all datasets, which is an excellent opportunity. 

For the responsibilities so far, we have our spreadsheet on google, right? So I suggest, that everybody has a look there, once we have the changes, to make sure all is going smoothly. Specifically add_forms_from_value, etc. will be crucial now.

**Comment by SimonGreenhill** [comment]
yes, we already have things left behind in lexibank-alpha, so don't want anything lost in <2 as well.
Can we write up a short email explaining what exactly should be changed?

**Comment by SimonGreenhill** [comment]
(See also my proposal email re lexibot which I think can help here)

**Comment by LinguList** [comment]
Yes, I'll need some time to think of how to best address the splitting behavior, which also needs mods in pylexibank. IN fact, I think I sent out an email on pylexibank after my major changes to add_forms and the like, but I think this time, what we should really do is:

1. fix lexibank for the new version 
2. set up patrons for all datasets there (and make list of datasets that are in the stack, without patron, for example, to be added later)
3. send around instructions on what to fix
4. make a code-sprint week (or two weeks) to fix things and have 1 other person review the data

I had the impression that my changes to pylexibank were lost in the many emails we write around, and also due to the fact that there was no direct follow-up on this. I think the best way to address this now is to commit on a two-days adjustment phase, where every lexibanker needs to learn the new drill.

We can do that in the first weeks of november, until then, we'd update lexibank.

**Comment by xrotwang** [comment]
@SimonGreenhill @LinguList `cldfbench` is progressing nicely right now, but replacing the corresponding functionality in `pylexibank` with stuff that's now in `cldfbench` will
- break things
- take some time (a couple of **days**, not just hours).

So what I'd need is a maintenance window of - say - a week, to do this. Ideally, the outcome would be
- `pylexibank 2.0rc1`
- `cldfbench 1.0rc1`
- a tutorial and a migration guide

**Comment by xrotwang** [comment]
@LinguList oh, and a `clldutils 3` compatible bug-fix release of `lingpy` would be nice.

**Comment by LinguList** [comment]
Yes, we look into the bugfix next week, I could do it by, say, Wednesday next week (but you might need to help me of how to fix some things).

And as to pylexibank-2.0: I would like to join in there and add my suggestions (or discuss them) on how to pass the splitting characters (used in split_forms) as well as the brackets (to delete from within a bracket, etc) as a major attribute of the class (I think this will make things more transparent). Is this okay with you, @xrotwang ?

Ah: and we may want to look at open issues to see if we can address some of them as well, right?

**Comment by xrotwang** [comment]
@LinguList yes,no problem. It would probably be good to have the behaviour documented in pseudo-code, or implemented in self-contained functions. While working on cldfbench I figured it is better to decouple lexibank dataset and cldf dataset a bit more. Right now, I have a `CLDFWriter` class, that doesn't know about the source dataset, and is only a small wrapper around a CLDF dataset. I'm not sure we'd put all these "add_..." methods on a subclass of this again.

**Comment by SimonGreenhill** [comment]
Yes, lots of issues here would be nice to have in pylexibank -- especially anything checking/validating stuff. We know a lot more about datasets now with the CLICS process and I'm happy for you to refactor everything as necessary. 

Maybe once the cldfbench refactor is done and we get rc1, then we can all spend a day in the DLCE meeting room (physically or virtually) refactoring all the datasets.

**Comment by LinguList** [comment]
I just moved this to a new [issue](https://github.com/lexibank/pylexibank/issues/126) and we should start adding milestones.

**Pull request merged**
